### ISSUE TITLE
Add classless.de

### ISSUE THREAD

**Issue by myfonj** [dbohdan/classless-css#10]
HP: http://classless.de/ 
GH: https://github.com/emareg/classlesscss

It incorporates some Bootstrap-inspired classes _for grid and spacing_, but basically should be here IMO.

--- 
(Found accidentally while [searching for this list](https://www.google.com/search?q=classless+css&tbs=li:1).)

**Comment by dbohdan** [comment]
Thanks!  Added in 54eaa97.
