### ISSUE TITLE
Add Bamboo CSS

### ISSUE THREAD

**Issue by myfonj** [dbohdan/classless-css#12]
Demo: https://rilwis.github.io/bamboo/demo/
GH: https://github.com/rilwis/bamboo

Fork of new.css, for modern browsers, colour theme configurable through custom properties.

---

Encountered in this tweet: https://twitter.com/rilwis/status/1365689979863658508

**Comment by rilwis** [comment]
Thank you for adding Bamboo CSS!

**Comment by dbohdan** [comment]
Added in 3fded47.
