### ISSUE TITLE
Suggestion: Downstyler

### ISSUE THREAD

**Issue by waldyrious** [dbohdan/classless-css#13]
[Downstyler](https://github.com/waldyrious/downstyler) is a pet project of mine, so I'm not sure it is notable enough, but I've been maintaining it for a few years now, and feel that it fits the spirit of this compilation. Would it make sense to add it to the list?

**Comment by dbohdan** [comment]
Added!

**Comment by waldyrious** [comment]
Thanks for the fast response! I'd be happy to take any feedback, by the way — either specific to Downstyler, or general guidelines you've developed while exploring these styles.

Awesome project you've got here! 👍

**Comment by dbohdan** [comment]
Thanks!  I'd suggest adding a fallback font more common than Crimson Text but less generic than "serif" and styling `<input>` and `<button>` elements.  The defaults for the latter may not be what you expect.  For example, in [wkhtmltopdf](https://wkhtmltopdf.org/), the otherwise a modern browser I've adopted for screenshots, they are by default pretty crude.

**Comment by waldyrious** [comment]
Thank you! I'll try to set aside some time to work on improving these aspects soon.

**Comment by waldyrious** [comment]
> I'd suggest adding a fallback font more common than Crimson Text but less generic than "serif"

I've added FreeSerif in https://github.com/waldyrious/downstyler/pull/67. Any additional suggestions are welcome!

> and styling `<input>` and `<button>` elements.

That's one of the oldest open issues, actually: https://github.com/waldyrious/downstyler/issues/5. Not sure when I'll be able to tackle it, but it's definitely on my radar.

**Comment by waldyrious** [comment]
> I'd suggest [...] styling `<input>` and `<button>` elements.

@dbohdan I have (finally!) made improvements to the display of form elements. Could you please regenerate Downstyler's screenshot and thumbnail? And more importantly, let me know if you have any suggestions for further improvement in Downstyler's display of forms. Thanks! :D

**Comment by dbohdan** [comment]
Screenshot updated!
