### ISSUE TITLE
Can you add Milligram?

### ISSUE THREAD

**Issue by gingerlime** [dbohdan/classless-css#2]
https://milligram.io/

not affiliated in any way, but I used it before, and I thought it would be nice to include it.

Really awesome to be able to see screenshots of the same page at a glance. Nice idea!

**Comment by dbohdan** [comment]
Done in 582ac678869b88255d3b7d1a8070485270ce7a96.

>Really awesome to be able to see screenshots of the same page at a glance. Nice idea!

Thanks!
