### ISSUE TITLE
Add Almond.CSS

### ISSUE THREAD

**Issue by waldyrious** [dbohdan/classless-css#20]
- Repository: https://github.com/alvaromontoro/almond.css
- Demo: https://alvaromontoro.github.io/almond.css/demo/
- Description (from the [README](https://github.com/alvaromontoro/almond.css/blob/master/README.md)):
  > Almond.CSS is a collection of class-less CSS styles to make simple websites look better.
  
  > The main goals of this project are:
  > - Use only tags: no classes or IDs.
  > - (...)

/cc @alvaromontoro

**Comment by dbohdan** [comment]
Added in 3d69294.
