### ISSUE TITLE
Add SASS-ZERO

### ISSUE THREAD

**Issue by lazaronixon** [dbohdan/classless-css#21]
https://github.com/lazaronixon/sass-zero/

**Comment by waldyrious** [comment]
Can you expand on what makes it classless? From the [usage section](https://github.com/lazaronixon/sass-zero/#usage) in the README and the [example HTML file](https://github.com/lazaronixon/sass-zero/blob/master/Example.html), it certainly seems to rely quite a bit on classes... :thinking:.

**Comment by lazaronixon** [comment]
It comes with a optional style-sheet called "breadboard.scss" that basically sets design for html attributes. If you remove this breadboard.css it is even less, so you have a design system with many variables and utilities class everything optional

**Comment by lazaronixon** [comment]
Yes, but the framework in general is specific to ruby on rails.

**Comment by dbohdan** [comment]
Link? I need a CSS file to generate a screenshot.

**Comment by lazaronixon** [comment]
https://gist.githubusercontent.com/lazaronixon/1c7dee3748a98d3b9ab00cde5754cd92/raw/588d67ffc2bd36a5987c44c30d44c0cc873f7a27/sass_zero.css
