### ISSUE TITLE
Add 98.css

### ISSUE THREAD

**Issue by waldyrious** [dbohdan/classless-css#24]
[This](https://github.com/jdan/98.css) is not a fully classless stylesheet, but it's definitely class-light.

**Comment by dbohdan** [comment]
Hmm, you don't get much without classes. The headings look wrong enough they are basically unusable. 98.css  is cool, but I don't think it qualifies as class-light. 

Screenshot:
![98 css](https://github.com/dbohdan/classless-css/assets/3179832/5127ce56-64b5-4488-939f-9e17d0fb6836)

**Comment by waldyrious** [comment]
Interesting — thanks for investigating! I wonder if @jdan has any thoughts about whether this stylesheet (or a variant thereof) could be applied to plain HTML in a way that reproduced the Windows 98 look. Especially since the description in the README does claim (emphasis mine):

> 98.css is a CSS file that takes **semantic HTML** and makes it look pretty.

For example, the `<body>` could have a default gray background; a `<section>` could behave as a `<div class="window">`, and headings within could be styled as window title bars; and so on. The end result should be that a class-less HTML file could look like the demo at https://jdan.github.io/98.css/. Perhaps a combination of [style.css](https://github.com/jdan/98.css/blob/main/style.css) + [docs.css](https://github.com/jdan/98.css/blob/main/docs/docs.css)?
