### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jcbhmr** [dbohdan/classless-css#27]
Is this project still maintained? I notice that there's a bunch of open issues and some PRs.

![image](https://user-images.githubusercontent.com/61068799/216137679-8b1a91d8-ba92-4910-8fe0-a28a1cf2910f.png)

If it's not maintained, it might be helpful to mark it as "Archived" to signal to users (like me) that it's no longer an active project.

**Comment by dbohdan** [comment]
This repository is currently on hiatus as I am recovering from a major illness. I plan to continue maintaining it once I have sufficiently recovered. The war in Ukraine may prevent me from maintaining it for some time after my recovery (or permanently).

**Comment by jcbhmr** [comment]
Thanks for that information!
