### ISSUE TITLE
prunus: maintained fork of sakura

### ISSUE THREAD

**Issue by kovmir** [dbohdan/classless-css#29]
Could you please mention [prunus](https://github.com/kovmir/prunus) which is a fork of no longer maintained [sakura](https://github.com/oxalorg/sakura)?

**Comment by waldyrious** [comment]
Hey @kovmir — I am really happy you decided to create and maintain a fork of the sakura stylesheet, but IMHO we should give it some time —say, maybe a couple months or so— before considering it a maintained fork. I mean, there seems to be a single commit over the original repo's history so far, and the [commit](https://github.com/kovmir/prunus/commit/33f101dada594d7836221e777d844bd8f4fa8dfe) from the [first release](https://github.com/kovmir/prunus/releases/tag/v1.4.2) has been already [rewritten](https://github.com/kovmir/prunus/commit/9d62cfb0afc8d60a3627ff751c956e66cbf24552), which doesn't suggest a great deal of stability yet, to the point that IMO would justify listing the project in lists like this.

By the way, I don't mean to diminish the effort you already did with the large amount of changes in that commit, or discourage you from future changes. This is just my opinion as someone who's seen projects come and go over time. I hope other followers of this project will voice their own thoughts as well.

**Comment by kovmir** [comment]
I will re-open later.
