### ISSUE TITLE
I think Marx also fits the criteria for this list

### ISSUE THREAD

**Issue by mblode** [dbohdan/classless-css#3]
Here is the URL to the Marx repo: https://github.com/mblode/marx

Marx - The classless CSS reset (perfect for Communists).

Marx is a CSS stylesheet to be used in any projects (namely small ones). If you don't need the weight of heavy frameworks or you would just like to make an edible website quickly, Marx is perfect for you. It can be used out of the minified box but it can also be customised and styled through the use of HTML classes.

**Comment by dbohdan** [comment]
Added in e28d6bf28e2271e10cebf87d083ceb875736a2cf.  Тнаикs.
