### ISSUE TITLE
Suggestion: ChimeraCSS

### ISSUE THREAD

**Issue by SindreKjelsrud** [dbohdan/classless-css#30]
[ChimeraCSS](https://github.com/ChimeraCSS) is a project by my friend, [J0hans1](https://github.com/J0hans1)! I'm not sure it is notable enough, but he started with it this summer and has good motivation to continue maintaining it. Would it make sense to add it to the list?

Why:
- Classless CSS frameworks is great for building beautiful UI, without worrying about unresponsive and unacessible elements.
- Chimera does the element styling for you, which only leaves the layout to you.
- For building MVPs fast and building UI without a designsystem; Chimera is a great framework.

**Comment by dbohdan** [comment]
Sorry, ChimeraCSS is a little too new to add yet. Projects this new are just too likely to be abandoned regardless of how motivated their developers are. The framework itself looks okay, although I have found two issues I'll report. Please reopen this issue if it is maintained in six months.

**Comment by J0hans1** [comment]
Hi, this framework has been maintained and have had major improvements made to it since the issue was closed. Many issues have been resolved (including those reported by @dbohdan). I think Chimera may deserve another shot at the list, and that this issue should be reopened :)

**Comment by dbohdan** [comment]
It's good that it is being actively worked on (I saw the closed issues), but I said six months, and it has only been three weeks. The point of this delay is not the amount of work that can be done in six months but to prove sustained maintainer interest.

I honestly suggest you set an automatic reminder to ping me in March 2024.

**Comment by J0hans1** [comment]
I understand, sorry for the misunderstanding.

**Comment by SindreKjelsrud** [comment]
@dbohdan March 2024 has arrived, wanna take another look at ChimeraCSS??

**Comment by dbohdan** [comment]
Will do.

**Comment by dbohdan** [comment]
The framework looks good (it has noticeably improved from before), and now it has been maintained for a while. Adding.
