### ISSUE TITLE
Suggestion: Fylgja

### ISSUE THREAD

**Issue by GrimLink** [dbohdan/classless-css#31]
Hi please add Fylgja to this list 😉

Github: https://github.com/fylgja/fylgja
Site: https://fylgja.dev/

Fylgja is a Component based CSS framework, allowing the user to use what they need.
Most of Fylgja is Class-light and some Components are in Classless, a.k.a. Native Elements.

**Comment by waldyrious** [comment]
> Most of Fylgja is Class-light

What exactly do you mean by this? I checked the [base.css style](https://unpkg.com/fylgja@1.3.3/fylgja.css) and that alone contains thousands of class selectors... :thinking:

**Comment by GrimLink** [comment]
@waldyrious, thanks for engaging in the discussion. Let's clarify a few points. The 'base.css' style is not part of the core package. It's worth mentioning that 'fylgja.css', in the core, contains all styles including the utility classes, which is why it might seem a bit overloaded, but this a bundle CSS file.

Fylgja is designed as a CSS component framework, and importing it doesn't involve a single package import. However, if you're looking for a more minimal bundle import, you can check out these bundle CSS files instead:

- [fylgja-slim.css (contains everything except utility classes)](https://unpkg.com/fylgja@1.3.3/fylgja-slim.css)
- [fylgja-html.css (includes only native elements)](https://unpkg.com/fylgja@1.3.3/fylgja-html.css)

The key thing to remember is to treat each CSS component as a separate entity. You can find beter explanation on this on this approach on our [intro page](https://fylgja.dev/getting-started/). This flexibility allows you to fine-tune your import to match your project's specific needs. If you have any more questions or need further assistance, feel free to ask!"

**Comment by waldyrious** [comment]
Thanks for the explanation and the two links — that's pretty useful to get a sense of how a minimal, classless version of Fylgja looks like :+1:

**Comment by dbohdan** [comment]
I think Fylgja qualifies. Do you have a documentation page on class-light usage? If you don't, could you add one? I wouldn't realize this was a class-light framework from a quick look at the site or the GitHub repo. This is not hard requirement for adding the framework.

[fylgja.css](https://github.com/dbohdan/classless-css/assets/3179832/000ce742-73fb-469e-8d37-d98ee348f8da) from the CDN looks right on my [test page](https://github.com/dbohdan/classless-css/blob/ebc4436f6c40bb9f31f46947b2446f49330e62e8/screenshot-page.html). However, [fylgja-html.css](https://github.com/dbohdan/classless-css/assets/3179832/4f5d2667-ab07-4b89-a072-09a068bbbd81) that you linked has an apparent issue. The left page margin is too thin. Does it expect a content wrapper with a different class/id/tag?

**Comment by dbohdan** [comment]
All right. Please ping me when you complete those updates.

**Comment by GrimLink** [comment]
Okay, that took a little longer than I wanted, @dbohdan.

But everything is here:

- Renamed the feature page to [Native Elements (Classless)](https://fylgja.dev/features/native-styles/), also added the same classless reference on the github page
- Added a guide for [Classless Setup](https://fylgja.dev/guides/classless-setup/)
- And last but not least, a codepen for this awesome list: https://codepen.io/Fylgja/pen/ExGOZaE

**Comment by waldyrious** [comment]
Hey @GrimLink, I hope I don't come off as too nagging, but is there any chance there could be a more compact version of [fylgja-html.css](https://fylgja.dev/guides/classless-setup/#the-alternative-importsetup-option) that omits the class-only styles like `.control-switch` and `.backdrop`, as well as the class-based alternatives to native selectors, like `.h1` in addition to `h1`, and `.is-disabled` vs. `:disabled`? Something like [this](https://editor.mergely.com/vaJeXPH6).

That would make the resulting stylesheet more lightweight, and would allow using it in a truly classless way (for those who may want such a thing, of course).

**Comment by GrimLink** [comment]
@waldyrious No, it's not even close to nagging. This is a good question.

I plan to do this for version 2 of Fylgja, but I could add it as a feature flag if you need it sooner. Feel free to open an issue, and I'll try to add it soon. Unfortunately, I have very little time right now due to all the Magento-related work I have to do. 😅

**Comment by waldyrious** [comment]
No rush, just a suggestion! I'm glad to hear you'll consider it :) looking forward to v2! :D
