### ISSUE TITLE
Barrel.css?

### ISSUE THREAD

**Issue by EternityForest** [dbohdan/classless-css#33]
Working on a class-light CSS theme, would this be a good fit for inclusion?  It can technically be used drop-in with OK results, but it does require a small number of simple classes for the best look.

Link:https://eternityforest.github.io/barrel.css/

![image](https://github.com/dbohdan/classless-css/assets/758047/c792bdb6-7973-43f2-a9cd-6df8a2140c98)

Hacking together a quick test on the standard page looks OK if kind of dated, mostly becayse the framework expects that content goes in a .window class element for the nice background, as it's designed for apps, where you might have multiple separate windows within a main tag.

![image](https://github.com/dbohdan/classless-css/assets/758047/75b2bf9a-94a0-478e-add7-e4e15030eff0)

**Comment by dbohdan** [comment]
This is fit for inclusion. Requiring to add a class on a container tag is fine according to the repository's definition of "class-light". The default theme looks okay with `<section id="content" container class="window paper">` ([screenshot](https://github.com/dbohdan/classless-css/assets/3179832/25d2fbe7-ed18-4b75-b1bc-e268b73fe375)). However, other themes like Banderole look wrong (not centered or limited in width; [screenshot](https://github.com/dbohdan/classless-css/assets/3179832/fc142770-8ef9-4551-ab50-fe036b0c06ae)). That's with the following HTML: [`screenshot-page.html`](https://github.com/dbohdan/classless-css/files/14179377/screenshot-page.html.txt). Could you debug this?

I would also suggest an addition to https://eternityforest.github.io/barrel.css/: it would help if underneath the theme-selection buttons it had a text field that showed the current theme URL that the user could copy.

**Comment by EternityForest** [comment]
Thank you for the feedback! I will look into debugging these test cases,
they definitely seem to be important.

**Comment by EternityForest** [comment]
Found the issue!  The test HTML only includes the banderole theme, but not barrel.css itself.  The theme CSS files are mostly variable overides.  Including barrel.css and banderole in the linked test image gives the following:

![Screenshot from 2024-02-13 00-56-49](https://github.com/dbohdan/classless-css/assets/758047/9b57579a-ec8a-4f76-8b59-a327663404de)
