### ISSUE TITLE
How about Beer CSS?

### ISSUE THREAD

**Issue by leonardorafael** [dbohdan/classless-css#35]
Hi, Beer CSS Framework seems a good candidate to add in class-light list.

Repository
https://github.com/beercss/beercss

Page
https://www.beercss.com

**Comment by dbohdan** [comment]
The demo page screenshot doesn't look good. The form elements are weird, and the vertical spacing isn't right. I have added the class `responsive` to `<main>`. This framework probably requires more classes than I would like for "class-light".

![Beer CSS screenshot](https://github.com/dbohdan/classless-css/assets/3179832/91ac37a7-eb7e-4ae7-96db-a6a505125469)

**Comment by leonardorafael** [comment]
Hmmm, yes the demo page is weird. It seems the demo page at all doesn't fit well for the material design system.

There are no doubts that Beer CSS is a class-light approach (semantic html + small set of global utility classes) has about 100 classes in total.

I understand that Beer CSS doesn't fit well here, anyway thanks for the feedback. I will close this issue 👍.
