### ISSUE TITLE
Warning: Picnic uses different HTML for checkboxes

### ISSUE THREAD

**Issue by shunlog** [dbohdan/classless-css#37]
I think there should be a warning in the [Picnic)](https://github.com/dbohdan/classless-css#picnic-css) section that it's "difficult to drop in an already created project". 

One would assume that all the stylesheets in this repo can be dropped in easily. However Picnic can't. For example, It needs [special construction](https://picnicss.com/documentation#checkbox) to display a checkbox. The vanilla checkboxes are simply hidden. There is a warning in Picnic repo, but it's easy to miss.

**Comment by dbohdan** [comment]
Thanks for reporting this. It is an important caveat for potential users. I'll add a warning.

One could say Picnic dropped classes in favor of [structural typing](https://en.wikipedia.org/wiki/Structural_type_system). :-) I'll keep it on the list, but it's an unusual edge-case.
