### ISSUE TITLE
Add Beer CSS?

### ISSUE THREAD

**Issue by leonardorafael** [dbohdan/classless-css#43]
Hi @dbohdan 

I want to know if [Beer CSS](https://www.beercss.com) fits well here (maybe in class-light?). 
I developed a codepen with your template below.
I will be awaiting a response from you, positive or negative (any response, it's ok for me).

https://codepen.io/leo-bnu/pen/GRbjppY

![cdpn io_leo-bnu_fullpage_GRbjppY_nocache=true view= (4)](https://github.com/user-attachments/assets/33219b27-0dec-427f-8a9e-429db4a59549)
![cdpn io_leo-bnu_fullpage_GRbjppY_nocache=true view= (3)](https://github.com/user-attachments/assets/0a074f89-2913-493d-b9ac-f6a193d18a81)

**Comment by dbohdan** [comment]
Hello! I have actually tried Beer CSS to see if I should add it. I thought it looked pretty good. Sorry, don't think it qualifies as class-light. You really need classes to achieve the advertised look.

I noticed what I consider a flaw when I tried Beer CSS: it uses a bi-state dark mode switch. Think about adopting a [tri-state](https://brandur.org/fragments/dark-mode-notes#tri-state) switch.
